version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/