version: '3'
services:
  gateway:
    build:
      dockerfile: Dockerfile
      context: ./server/gateway
    ports:
      - '8080:8080'
  problems:
    build: 
      dockerfile: Dockerfile
      context: ./server/problems
    ports:
      - '3000:3000'